apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /srv/data1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /srv/data2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /srv/data3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /srv/data4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5
spec:
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /srv/data5
