version: "3"
services:
    flask_mini:
        build: .
        command: ./server.py
        container_name: flask_mini

    nginx:
        image: nginx
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
        - 80:80
        container_name: nginx

